name: Deploy to AWS EC2

on:
  push:
    tags:
      - "v*-dev-deploy"

  workflow_dispatch:
    inputs:
      deploy_version:
        type: string
        description: Version to deploy in format vX.Y.Z
      deploy_environment:
        type: choice
        description: Deploy Environment
        options:
          - dev

env:
  AWS_REGION: ${{ secrets.AWS_ECR_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPO_NAME }}
  IMAGE_NAME: webapp3_api
  EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}

jobs:
  tagify:
    name: Get Tag
    runs-on: ubuntu-latest
    outputs:
      the_tag: ${{ steps.deploy_tag.outputs.TAG_NAME }}
    steps:
      - name: Extract Deploy Tag (Push Event)
        if: github.event_name == 'push'
        run: |
          full_tag=${GITHUB_REF#refs/*/}
          deploy_tag=${full_tag%-deploy}
          echo "VERSION=${deploy_tag}" >> "$GITHUB_ENV"

      - name: Extract Deploy Tag (Manual Trigger)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "VERSION=${{ github.event.inputs.deploy_version }}-${{ github.event.inputs.deploy_environment }}" >> "$GITHUB_ENV"

      - name: Set Output Variable
        id: deploy_tag
        run: |
          echo "TAG_NAME=${{ env.VERSION }}" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to EC2
    needs: [tagify]
    runs-on: ubuntu-latest
    if: endsWith(needs.tagify.outputs.the_tag, 'dev')
    env:
      TAG_VERSION: ${{ needs.tagify.outputs.the_tag }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/DeploymentKey.pem
          chmod 600 ~/.ssh/DeploymentKey.pem

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_ECR_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Deploy Application on EC2
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          TAG_VERSION: ${{ needs.tagify.outputs.the_tag }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/DeploymentKey.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << EOF
            set -e
            
            echo "Logging into ECR..."
            aws ecr get-login-password --region ${{ secrets.AWS_ECR_REGION }} | \
              docker login --username AWS --password-stdin $REGISTRY
        
            echo "Stopping and removing existing container..."
            docker stop $IMAGE_NAME || true
            docker rm -f $IMAGE_NAME || true
        
            echo "Pulling latest image..."
            docker pull $REGISTRY/webapplication3:latest 
            echo "$REGISTRY/webapplication3:latest "
            echo "Running new container..."
            docker run -d -p 8080:8080 --name $IMAGE_NAME \
              $REGISTRY/$ECR_REPO_NAME:$TAG_VERSION
          EOF
      - name: Cleanup SSH Key
        run: rm -f ~/.ssh/DeploymentKey.pem
